// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v3.1.3
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_codegen.cpp:148

#ifndef _TAO_IDL__TMP__CAMERAC_H_
#define _TAO_IDL__TMP__CAMERAC_H_


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "tao/Object.h"
#include "tao/AnyTypeCode/TypeCode.h"
#include "tao/AnyTypeCode/TypeCode_Constants.h"
#include "tao/String_Manager_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/Object_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "baciC.h"
#include "TypesC.h"

#if TAO_MAJOR_VERSION != 3 || TAO_MINOR_VERSION != 1 || TAO_MICRO_VERSION != 3
#error This file should be regenerated with TAO_IDL
#endif
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_root/root_ch.cpp:155


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<typename T> class Narrow_Utils;
}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:34

namespace CAMERA_MODULE
{
  // TAO_IDL - Generated from
  // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_interface.cpp:742

  

#if !defined (_CAMERA_MODULE_CAMERA__VAR_OUT_CH_)
#define _CAMERA_MODULE_CAMERA__VAR_OUT_CH_

  class Camera;
  using Camera_ptr = Camera*;
  using Camera_var = TAO_Objref_Var_T<Camera>;
  using Camera_out = TAO_Objref_Out_T<Camera>;

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:39

  

  class  Camera
    : public virtual ::ACS::CharacteristicComponent
  
  {
  public:
    friend class TAO::Narrow_Utils<Camera>;
    // TAO_IDL - Generated from
    // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_type.cpp:297

    using _ptr_type = Camera_ptr;
    using _var_type = Camera_var;
    using _out_type = Camera_out;

    static void _tao_any_destructor (void *);

    // The static operations.
    static Camera_ptr _duplicate (Camera_ptr obj);

    static void _tao_release (Camera_ptr obj);

    static Camera_ptr _narrow (::CORBA::Object_ptr obj);
    static Camera_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static Camera_ptr _nil ();

    virtual ::TYPES::ImageType * getFrame (
      const char * exposureTime,
      const char * iso);

    virtual void on ();

    virtual void off ();

    virtual ::ACS::RWstring_ptr isoSpeed ();

    virtual ::ACS::RWstring_ptr shutterSpeed ();

    
    // TAO_IDL - Generated from
    // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id () const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Concrete interface only.
    Camera ();

    // Concrete non-local interface only.
    Camera (::IOP::IOR *ior, TAO_ORB_Core *orb_core);
    
    // Non-local interface only.
    Camera (
        TAO_Stub *objref,
        ::CORBA::Boolean _tao_collocated = false,
        TAO_Abstract_ServantBase *servant = nullptr,
        TAO_ORB_Core *orb_core = nullptr);

    virtual ~Camera () = default;
  
  private:
    // Private and unimplemented for concrete interfaces.
    Camera (const Camera &) = delete;
    Camera (Camera &&) = delete;
    Camera &operator= (const Camera &) = delete;
    Camera &operator= (Camera &&) = delete;
  };
  // TAO_IDL - Generated from
  // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_typecode/typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_Camera;


// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:62


} // module CAMERA_MODULE
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:64



TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
  // TAO_IDL - Generated from
  // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:142

  

#if !defined (_CAMERA_MODULE_CAMERA__ARG_TRAITS_)
#define _CAMERA_MODULE_CAMERA__ARG_TRAITS_

  template<>
  class  Arg_Traits< ::CAMERA_MODULE::Camera>
    : public Object_Arg_Traits_T<
        ::CAMERA_MODULE::Camera_ptr,
        ::CAMERA_MODULE::Camera_var,
        ::CAMERA_MODULE::Camera_out,
        TAO::Objref_Traits<CAMERA_MODULE::Camera>,
        TAO::Any_Insert_Policy_Stream>
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_traits.cpp:58



TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_CAMERA_MODULE_CAMERA__TRAITS_)
#define _CAMERA_MODULE_CAMERA__TRAITS_

  template<>
  struct  Objref_Traits< ::CAMERA_MODULE::Camera>
  {
    static ::CAMERA_MODULE::Camera_ptr duplicate (::CAMERA_MODULE::Camera_ptr p);
    static void release (::CAMERA_MODULE::Camera_ptr p);
    static ::CAMERA_MODULE::Camera_ptr nil ();
    static ::CORBA::Boolean marshal (const ::CAMERA_MODULE::Camera_ptr p,TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/any_op_ch.cpp:40




TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {

 void operator<<= (::CORBA::Any &, CAMERA_MODULE::Camera_ptr); // copying
 void operator<<= (::CORBA::Any &, CAMERA_MODULE::Camera_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, CAMERA_MODULE::Camera_ptr &);
}
TAO_END_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/cdr_op_ch.cpp:40



TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const CAMERA_MODULE::Camera_ptr );
 ::CORBA::Boolean operator>> (TAO_InputCDR &, CAMERA_MODULE::Camera_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_codegen.cpp:1648

#if defined (__ACE_INLINE__)
#include "CameraC.inl"
#endif /* defined INLINE */

#endif /* ifndef */

