// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v3.1.3
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_codegen.cpp:148

#ifndef _TAO_IDL__TMP__CONSOLEC_H_
#define _TAO_IDL__TMP__CONSOLEC_H_


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/Object_Argument_T.h"
#include "tao/Special_Basic_Arguments.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "acscomponentC.h"
#include "TypesC.h"
#include "SYSTEMErrC.h"

#if TAO_MAJOR_VERSION != 3 || TAO_MINOR_VERSION != 1 || TAO_MICRO_VERSION != 3
#error This file should be regenerated with TAO_IDL
#endif
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_root/root_ch.cpp:155


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<typename T> class Narrow_Utils;
}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:34

namespace CONSOLE_MODULE
{
  // TAO_IDL - Generated from
  // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_interface.cpp:742

  

#if !defined (_CONSOLE_MODULE_CONSOLE__VAR_OUT_CH_)
#define _CONSOLE_MODULE_CONSOLE__VAR_OUT_CH_

  class Console;
  using Console_ptr = Console*;
  using Console_var = TAO_Objref_Var_T<Console>;
  using Console_out = TAO_Objref_Out_T<Console>;

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:39

  

  class  Console
    : public virtual ::ACS::ACSComponent
  
  {
  public:
    friend class TAO::Narrow_Utils<Console>;
    // TAO_IDL - Generated from
    // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_type.cpp:297

    using _ptr_type = Console_ptr;
    using _var_type = Console_var;
    using _out_type = Console_out;

    static void _tao_any_destructor (void *);

    // The static operations.
    static Console_ptr _duplicate (Console_ptr obj);

    static void _tao_release (Console_ptr obj);

    static Console_ptr _narrow (::CORBA::Object_ptr obj);
    static Console_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static Console_ptr _nil ();

    virtual void setMode (
      ::CORBA::Boolean mode);

    virtual ::CORBA::Boolean getMode ();

    virtual void cameraOn ();

    virtual void cameraOff ();

    virtual void moveTelescope (
      const ::TYPES::Position & coordinates);

    virtual ::TYPES::Position getTelescopePosition ();

    virtual ::TYPES::ImageType * getCameraImage ();

    virtual void setRGB (
      const ::TYPES::RGB & rgbConfig);

    virtual void setPixelBias (
      ::CORBA::Long bias);

    virtual void setResetLevel (
      ::CORBA::Long resetLevel);

    
    // TAO_IDL - Generated from
    // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id () const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Concrete interface only.
    Console ();

    // Concrete non-local interface only.
    Console (::IOP::IOR *ior, TAO_ORB_Core *orb_core);
    
    // Non-local interface only.
    Console (
        TAO_Stub *objref,
        ::CORBA::Boolean _tao_collocated = false,
        TAO_Abstract_ServantBase *servant = nullptr,
        TAO_ORB_Core *orb_core = nullptr);

    virtual ~Console () = default;
  
  private:
    // Private and unimplemented for concrete interfaces.
    Console (const Console &) = delete;
    Console (Console &&) = delete;
    Console &operator= (const Console &) = delete;
    Console &operator= (Console &&) = delete;
  };
  // TAO_IDL - Generated from
  // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_typecode/typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_Console;


// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:62


} // module CONSOLE_MODULE
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:64



TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
  // TAO_IDL - Generated from
  // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:142

  

#if !defined (_CONSOLE_MODULE_CONSOLE__ARG_TRAITS_)
#define _CONSOLE_MODULE_CONSOLE__ARG_TRAITS_

  template<>
  class  Arg_Traits< ::CONSOLE_MODULE::Console>
    : public Object_Arg_Traits_T<
        ::CONSOLE_MODULE::Console_ptr,
        ::CONSOLE_MODULE::Console_var,
        ::CONSOLE_MODULE::Console_out,
        TAO::Objref_Traits<CONSOLE_MODULE::Console>,
        TAO::Any_Insert_Policy_Stream>
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_traits.cpp:58



TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_CONSOLE_MODULE_CONSOLE__TRAITS_)
#define _CONSOLE_MODULE_CONSOLE__TRAITS_

  template<>
  struct  Objref_Traits< ::CONSOLE_MODULE::Console>
  {
    static ::CONSOLE_MODULE::Console_ptr duplicate (::CONSOLE_MODULE::Console_ptr p);
    static void release (::CONSOLE_MODULE::Console_ptr p);
    static ::CONSOLE_MODULE::Console_ptr nil ();
    static ::CORBA::Boolean marshal (const ::CONSOLE_MODULE::Console_ptr p,TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/any_op_ch.cpp:40




TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {

 void operator<<= (::CORBA::Any &, CONSOLE_MODULE::Console_ptr); // copying
 void operator<<= (::CORBA::Any &, CONSOLE_MODULE::Console_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, CONSOLE_MODULE::Console_ptr &);
}
TAO_END_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/cdr_op_ch.cpp:40



TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const CONSOLE_MODULE::Console_ptr );
 ::CORBA::Boolean operator>> (TAO_InputCDR &, CONSOLE_MODULE::Console_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_codegen.cpp:1648

#if defined (__ACE_INLINE__)
#include "ConsoleC.inl"
#endif /* defined INLINE */

#endif /* ifndef */

