// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v3.1.3
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_codegen.cpp:148

#ifndef _TAO_IDL__TMP__DATABASEC_H_
#define _TAO_IDL__TMP__DATABASEC_H_


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/Object_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "acscomponentC.h"
#include "TypesC.h"
#include "SYSTEMErrC.h"

#if TAO_MAJOR_VERSION != 3 || TAO_MINOR_VERSION != 1 || TAO_MICRO_VERSION != 3
#error This file should be regenerated with TAO_IDL
#endif
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_root/root_ch.cpp:155


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<typename T> class Narrow_Utils;
}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:34

namespace DATABASE_MODULE
{
  // TAO_IDL - Generated from
  // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_interface.cpp:742

  

#if !defined (_DATABASE_MODULE_DATABASE__VAR_OUT_CH_)
#define _DATABASE_MODULE_DATABASE__VAR_OUT_CH_

  class DataBase;
  using DataBase_ptr = DataBase*;
  using DataBase_var = TAO_Objref_Var_T<DataBase>;
  using DataBase_out = TAO_Objref_Out_T<DataBase>;

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:39

  

  class  DataBase
    : public virtual ::ACS::ACSComponent
  
  {
  public:
    friend class TAO::Narrow_Utils<DataBase>;
    // TAO_IDL - Generated from
    // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_type.cpp:297

    using _ptr_type = DataBase_ptr;
    using _var_type = DataBase_var;
    using _out_type = DataBase_out;

    static void _tao_any_destructor (void *);

    // The static operations.
    static DataBase_ptr _duplicate (DataBase_ptr obj);

    static void _tao_release (DataBase_ptr obj);

    static DataBase_ptr _narrow (::CORBA::Object_ptr obj);
    static DataBase_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static DataBase_ptr _nil ();

    virtual ::CORBA::Long storeProposal (
      const ::TYPES::TargetList & targets);
    // TAO_IDL - Generated from
    // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_constant/constant_ch.cpp:34

    

    static const CORBA::Long STATUS_INITIAL_PROPOSAL = 0;
    // TAO_IDL - Generated from
    // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_constant/constant_ch.cpp:34

    

    static const CORBA::Long STATUS_NO_SUCH_PROPOSAL = -999;

    virtual ::CORBA::Long getProposalStatus (
      ::CORBA::Long pid);

    virtual void removeProposal (
      ::CORBA::Long pid);

    virtual ::TYPES::ImageList * getProposalObservations (
      ::CORBA::Long pid);

    virtual ::TYPES::ProposalList * getProposals ();

    virtual void setProposalStatus (
      ::CORBA::Long pid,
      ::CORBA::Long status);

    virtual void storeImage (
      ::CORBA::Long pid,
      ::CORBA::Long tid,
      const ::TYPES::ImageType & image);

    virtual void clean ();

    
    // TAO_IDL - Generated from
    // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id () const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Concrete interface only.
    DataBase ();

    // Concrete non-local interface only.
    DataBase (::IOP::IOR *ior, TAO_ORB_Core *orb_core);
    
    // Non-local interface only.
    DataBase (
        TAO_Stub *objref,
        ::CORBA::Boolean _tao_collocated = false,
        TAO_Abstract_ServantBase *servant = nullptr,
        TAO_ORB_Core *orb_core = nullptr);

    virtual ~DataBase () = default;
  
  private:
    // Private and unimplemented for concrete interfaces.
    DataBase (const DataBase &) = delete;
    DataBase (DataBase &&) = delete;
    DataBase &operator= (const DataBase &) = delete;
    DataBase &operator= (DataBase &&) = delete;
  };
  // TAO_IDL - Generated from
  // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_typecode/typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_DataBase;


// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:62


} // module DATABASE_MODULE
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:64



TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
  // TAO_IDL - Generated from
  // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:142

  

#if !defined (_DATABASE_MODULE_DATABASE__ARG_TRAITS_)
#define _DATABASE_MODULE_DATABASE__ARG_TRAITS_

  template<>
  class  Arg_Traits< ::DATABASE_MODULE::DataBase>
    : public Object_Arg_Traits_T<
        ::DATABASE_MODULE::DataBase_ptr,
        ::DATABASE_MODULE::DataBase_var,
        ::DATABASE_MODULE::DataBase_out,
        TAO::Objref_Traits<DATABASE_MODULE::DataBase>,
        TAO::Any_Insert_Policy_Stream>
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_traits.cpp:58



TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_DATABASE_MODULE_DATABASE__TRAITS_)
#define _DATABASE_MODULE_DATABASE__TRAITS_

  template<>
  struct  Objref_Traits< ::DATABASE_MODULE::DataBase>
  {
    static ::DATABASE_MODULE::DataBase_ptr duplicate (::DATABASE_MODULE::DataBase_ptr p);
    static void release (::DATABASE_MODULE::DataBase_ptr p);
    static ::DATABASE_MODULE::DataBase_ptr nil ();
    static ::CORBA::Boolean marshal (const ::DATABASE_MODULE::DataBase_ptr p,TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/any_op_ch.cpp:40




TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {

 void operator<<= (::CORBA::Any &, DATABASE_MODULE::DataBase_ptr); // copying
 void operator<<= (::CORBA::Any &, DATABASE_MODULE::DataBase_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DATABASE_MODULE::DataBase_ptr &);
}
TAO_END_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/cdr_op_ch.cpp:40



TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DATABASE_MODULE::DataBase_ptr );
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DATABASE_MODULE::DataBase_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_codegen.cpp:1648

#if defined (__ACE_INLINE__)
#include "DataBaseC.inl"
#endif /* defined INLINE */

#endif /* ifndef */

