// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v3.1.3
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_codegen.cpp:372


#include "DataBaseC.h"
#include "tao/AnyTypeCode/Null_RefCount_Policy.h"
#include "tao/AnyTypeCode/TypeCode_Constants.h"
#include "tao/AnyTypeCode/Alias_TypeCode_Static.h"
#include "tao/AnyTypeCode/Objref_TypeCode_Static.h"
#include "tao/CDR.h"
#include "tao/Exception_Data.h"
#include "tao/Invocation_Adapter.h"
#include "tao/Object_T.h"
#include "tao/CDR.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/AnyTypeCode/Any_Impl_T.h"
#include "cstring"

#if !defined (__ACE_INLINE__)
#include "DataBaseC.inl"
#endif /* !defined INLINE */
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for DATABASE_MODULE::DataBase.

DATABASE_MODULE::DataBase_ptr
TAO::Objref_Traits<DATABASE_MODULE::DataBase>::duplicate (DATABASE_MODULE::DataBase_ptr p)
{
  return DATABASE_MODULE::DataBase::_duplicate (p);
}

void
TAO::Objref_Traits<DATABASE_MODULE::DataBase>::release (DATABASE_MODULE::DataBase_ptr p)
{
  ::CORBA::release (p);
}

DATABASE_MODULE::DataBase_ptr
TAO::Objref_Traits<DATABASE_MODULE::DataBase>::nil ()
{
  return DATABASE_MODULE::DataBase::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<DATABASE_MODULE::DataBase>::marshal (const DATABASE_MODULE::DataBase_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/operation_cs.cpp:87

::CORBA::Long
DATABASE_MODULE::DataBase::storeProposal (
  const ::TYPES::TargetList & targets)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< ::CORBA::Long>::ret_val _tao_retval;
  TAO::Arg_Traits< ::TYPES::TargetList>::in_arg_val _tao_targets (targets);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      std::addressof(_tao_retval),
      std::addressof(_tao_targets)
    };

  TAO::Invocation_Adapter _invocation_call (
      this,
      _the_tao_operation_signature,
      2,
      "storeProposal",
      13,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
      
    );

  _invocation_call.invoke (nullptr, 0);

  return _tao_retval.retn ();
}
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_constant/constant_cs.cpp:53



const CORBA::Long DATABASE_MODULE::DataBase::STATUS_INITIAL_PROPOSAL;
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_constant/constant_cs.cpp:53



const CORBA::Long DATABASE_MODULE::DataBase::STATUS_NO_SUCH_PROPOSAL;
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/operation_cs.cpp:87

::CORBA::Long
DATABASE_MODULE::DataBase::getProposalStatus (
  ::CORBA::Long pid)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< ::CORBA::Long>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Long>::in_arg_val _tao_pid (pid);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      std::addressof(_tao_retval),
      std::addressof(_tao_pid)
    };

  TAO::Invocation_Adapter _invocation_call (
      this,
      _the_tao_operation_signature,
      2,
      "getProposalStatus",
      17,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
      
    );

  _invocation_call.invoke (nullptr, 0);

  return _tao_retval.retn ();
}
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/operation_cs.cpp:87

void
DATABASE_MODULE::DataBase::removeProposal (
  ::CORBA::Long pid)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Long>::in_arg_val _tao_pid (pid);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      std::addressof(_tao_retval),
      std::addressof(_tao_pid)
    };

  TAO::Invocation_Adapter _invocation_call (
      this,
      _the_tao_operation_signature,
      2,
      "removeProposal",
      14,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
      
    );

  _invocation_call.invoke (nullptr, 0);
}
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/operation_cs.cpp:87

::TYPES::ImageList *
DATABASE_MODULE::DataBase::getProposalObservations (
  ::CORBA::Long pid)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< ::TYPES::ImageList>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Long>::in_arg_val _tao_pid (pid);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      std::addressof(_tao_retval),
      std::addressof(_tao_pid)
    };

  static TAO::Exception_Data
  _tao_DATABASE_MODULE_DataBase_getProposalObservations_exceptiondata [] = 
    {
      {
        "IDL:acsws/SYSTEMErr/ProposalNotYetReadyEx:1.0",
        SYSTEMErr::ProposalNotYetReadyEx::_alloc
#if TAO_HAS_INTERCEPTORS == 1
        , SYSTEMErr::_tc_ProposalNotYetReadyEx
#endif /* TAO_HAS_INTERCEPTORS */
      }
    };

  TAO::Invocation_Adapter _invocation_call (
      this,
      _the_tao_operation_signature,
      2,
      "getProposalObservations",
      23,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
      
    );

  _invocation_call.invoke (
      _tao_DATABASE_MODULE_DataBase_getProposalObservations_exceptiondata,
      1
    );

  return _tao_retval.retn ();
}
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/operation_cs.cpp:87

::TYPES::ProposalList *
DATABASE_MODULE::DataBase::getProposals ()
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< ::TYPES::ProposalList>::ret_val _tao_retval;

  TAO::Argument *_the_tao_operation_signature [] =
    {
      std::addressof(_tao_retval)
    };

  TAO::Invocation_Adapter _invocation_call (
      this,
      _the_tao_operation_signature,
      1,
      "getProposals",
      12,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY,
      TAO::TAO_TWOWAY_INVOCATION
      ,
      TAO::TAO_SYNCHRONOUS_INVOCATION,
      false
    );

  _invocation_call.invoke (nullptr, 0);

  return _tao_retval.retn ();
}
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/operation_cs.cpp:87

void
DATABASE_MODULE::DataBase::setProposalStatus (
  ::CORBA::Long pid,
  ::CORBA::Long status)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Long>::in_arg_val _tao_pid (pid);
  TAO::Arg_Traits< ::CORBA::Long>::in_arg_val _tao_status (status);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      std::addressof(_tao_retval),
      std::addressof(_tao_pid),
      std::addressof(_tao_status)
    };

  static TAO::Exception_Data
  _tao_DATABASE_MODULE_DataBase_setProposalStatus_exceptiondata [] = 
    {
      {
        "IDL:acsws/SYSTEMErr/InvalidProposalStatusTransitionEx:1.0",
        SYSTEMErr::InvalidProposalStatusTransitionEx::_alloc
#if TAO_HAS_INTERCEPTORS == 1
        , SYSTEMErr::_tc_InvalidProposalStatusTransitionEx
#endif /* TAO_HAS_INTERCEPTORS */
      }
    };

  TAO::Invocation_Adapter _invocation_call (
      this,
      _the_tao_operation_signature,
      3,
      "setProposalStatus",
      17,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
      
    );

  _invocation_call.invoke (
      _tao_DATABASE_MODULE_DataBase_setProposalStatus_exceptiondata,
      1
    );
}
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/operation_cs.cpp:87

void
DATABASE_MODULE::DataBase::storeImage (
  ::CORBA::Long pid,
  ::CORBA::Long tid,
  const ::TYPES::ImageType & image)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Long>::in_arg_val _tao_pid (pid);
  TAO::Arg_Traits< ::CORBA::Long>::in_arg_val _tao_tid (tid);
  TAO::Arg_Traits< ::TYPES::ImageType>::in_arg_val _tao_image (image);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      std::addressof(_tao_retval),
      std::addressof(_tao_pid),
      std::addressof(_tao_tid),
      std::addressof(_tao_image)
    };

  static TAO::Exception_Data
  _tao_DATABASE_MODULE_DataBase_storeImage_exceptiondata [] = 
    {
      {
        "IDL:acsws/SYSTEMErr/ImageAlreadyStoredEx:1.0",
        SYSTEMErr::ImageAlreadyStoredEx::_alloc
#if TAO_HAS_INTERCEPTORS == 1
        , SYSTEMErr::_tc_ImageAlreadyStoredEx
#endif /* TAO_HAS_INTERCEPTORS */
      },

      {
        "IDL:acsws/SYSTEMErr/ProposalDoesNotExistEx:1.0",
        SYSTEMErr::ProposalDoesNotExistEx::_alloc
#if TAO_HAS_INTERCEPTORS == 1
        , SYSTEMErr::_tc_ProposalDoesNotExistEx
#endif /* TAO_HAS_INTERCEPTORS */
      },

      {
        "IDL:acsws/SYSTEMErr/TargetDoesNotExistEx:1.0",
        SYSTEMErr::TargetDoesNotExistEx::_alloc
#if TAO_HAS_INTERCEPTORS == 1
        , SYSTEMErr::_tc_TargetDoesNotExistEx
#endif /* TAO_HAS_INTERCEPTORS */
      }
    };

  TAO::Invocation_Adapter _invocation_call (
      this,
      _the_tao_operation_signature,
      4,
      "storeImage",
      10,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
      
    );

  _invocation_call.invoke (
      _tao_DATABASE_MODULE_DataBase_storeImage_exceptiondata,
      3
    );
}
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/operation_cs.cpp:87

void
DATABASE_MODULE::DataBase::clean ()
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;

  TAO::Argument *_the_tao_operation_signature [] =
    {
      std::addressof(_tao_retval)
    };

  TAO::Invocation_Adapter _invocation_call (
      this,
      _the_tao_operation_signature,
      1,
      "clean",
      5,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY,
      TAO::TAO_TWOWAY_INVOCATION
      ,
      TAO::TAO_SYNCHRONOUS_INVOCATION,
      false
    );

  _invocation_call.invoke (nullptr, 0);
}

DATABASE_MODULE::DataBase::DataBase ()
{
}
void
DATABASE_MODULE::DataBase::_tao_any_destructor (void *_tao_void_pointer)
{
  DataBase *_tao_tmp_pointer =
    static_cast<DataBase *> (_tao_void_pointer);
  ::CORBA::release (_tao_tmp_pointer);
}

DATABASE_MODULE::DataBase_ptr
DATABASE_MODULE::DataBase::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TAO::Narrow_Utils<DataBase>::narrow (_tao_objref, "IDL:acsws/DATABASE_MODULE/DataBase:1.0");
}

DATABASE_MODULE::DataBase_ptr
DATABASE_MODULE::DataBase::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TAO::Narrow_Utils<DataBase>::unchecked_narrow (_tao_objref);
}

DATABASE_MODULE::DataBase_ptr
DATABASE_MODULE::DataBase::_nil ()
{
  return nullptr;
}

DATABASE_MODULE::DataBase_ptr
DATABASE_MODULE::DataBase::_duplicate (DataBase_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
DATABASE_MODULE::DataBase::_tao_release (DataBase_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
DATABASE_MODULE::DataBase::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:alma/ACS/ACSComponent:1.0") == 0 ||
      std::strcmp (value, "IDL:acsws/DATABASE_MODULE/DataBase:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* DATABASE_MODULE::DataBase::_interface_repository_id () const
{
  return "IDL:acsws/DATABASE_MODULE/DataBase:1.0";
}

::CORBA::Boolean
DATABASE_MODULE::DataBase::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_typecode/objref_typecode.cpp:68

static TAO::TypeCode::Objref<char const *,
                             TAO::Null_RefCount_Policy>
  _tao_tc_DATABASE_MODULE_DataBase (
    ::CORBA::tk_objref,
    "IDL:acsws/DATABASE_MODULE/DataBase:1.0",
    "DataBase");
  

namespace DATABASE_MODULE
{
  ::CORBA::TypeCode_ptr const _tc_DataBase =
    &_tao_tc_DATABASE_MODULE_DataBase;
}
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/any_op_cs.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<DATABASE_MODULE::DataBase>::to_object (
      ::CORBA::Object_ptr &_tao_elem) const
  {
    _tao_elem = ::CORBA::Object::_duplicate (this->value_);
    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {



/// Copying insertion.
void
operator<<= (
  ::CORBA::Any &_tao_any,
  DATABASE_MODULE::DataBase_ptr _tao_elem)
{
  DATABASE_MODULE::DataBase_ptr _tao_objptr =
    DATABASE_MODULE::DataBase::_duplicate (_tao_elem);
  _tao_any <<= std::addressof(_tao_objptr);
}

/// Non-copying insertion.
void
operator<<= (
  ::CORBA::Any &_tao_any,
  DATABASE_MODULE::DataBase_ptr *_tao_elem)
{
  TAO::Any_Impl_T<DATABASE_MODULE::DataBase>::insert (
    _tao_any,
    DATABASE_MODULE::DataBase::_tao_any_destructor,
    DATABASE_MODULE::_tc_DataBase,
    *_tao_elem);
}

::CORBA::Boolean
operator>>= (
    const ::CORBA::Any &_tao_any,
    DATABASE_MODULE::DataBase_ptr &_tao_elem)
{
  return
    TAO::Any_Impl_T<DATABASE_MODULE::DataBase>::extract (
        _tao_any,
        DATABASE_MODULE::DataBase::_tao_any_destructor,
        DATABASE_MODULE::_tc_DataBase,
        _tao_elem);
}

}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/cdr_op_cs.cpp:50


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const DATABASE_MODULE::DataBase_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    DATABASE_MODULE::DataBase_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;

  if (!(strm >> obj.inout ()))
    {
      return false;
    }
  
  // Narrow to the right type.
  _tao_objref = TAO::Narrow_Utils< ::DATABASE_MODULE::DataBase>::unchecked_narrow (obj.in ());

  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL



