// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v3.1.3
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_codegen.cpp:631

#ifndef _TAO_IDL__TMP__DATABASES_CPP_
#define _TAO_IDL__TMP__DATABASES_CPP_


#include "DataBaseS.h"
#include "tao/PortableServer/Operation_Table_Perfect_Hash.h"
#include "tao/PortableServer/Upcall_Command.h"
#include "tao/PortableServer/Upcall_Wrapper.h"
#include "tao/TAO_Server_Request.h"
#include "tao/ORB_Core.h"
#include "tao/Profile.h"
#include "tao/Stub.h"
#include "tao/IFR_Client_Adapter.h"
#include "tao/Object_T.h"
#include "tao/AnyTypeCode/TypeCode.h"
#include "tao/AnyTypeCode/DynamicC.h"
#include "tao/CDR.h"
#include "tao/operation_details.h"
#include "tao/PortableInterceptor.h"
#include "ace/Dynamic_Service.h"
#include "ace/Malloc_Allocator.h"
#include "cstring"
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_interface.cpp:1853

class TAO_DATABASE_MODULE_DataBase_Perfect_Hash_OpTable
  : public TAO_Perfect_Hash_OpTable
{
private:
  unsigned int hash (const char *str, unsigned int len) override;

public:
  const TAO_operation_db_entry * lookup (const char *str, unsigned int len) override;
};

/* C++ code produced by gperf version 2.8 (ACE version) */
/* Command-line: ace_gperf -m -M -J -c -C -D -E -T -f 0 -F 0,0 -a -o -t -p -K opname -L C++ -Z TAO_DATABASE_MODULE_DataBase_Perfect_Hash_OpTable -N lookup */

unsigned int
TAO_DATABASE_MODULE_DataBase_Perfect_Hash_OpTable::hash (const char *str, unsigned int len)
{
  static constexpr unsigned char asso_values[] =
    {
     34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
     34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
     34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
     34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
     34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
     34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
     34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
     34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
     34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
     34, 34, 34, 34, 34,  5, 34, 15, 34,  0,
      0,  0, 34, 10, 34, 34, 34, 34,  0, 34,
      0, 34, 34, 34, 15,  0,  5, 34, 34, 34,
     34, 34, 34, 34, 34, 34, 34, 34,
    };
  return len + asso_values[static_cast<int>(str[len - 1])] + asso_values[static_cast<int>(str[0])];
}

const TAO_operation_db_entry *
TAO_DATABASE_MODULE_DataBase_Perfect_Hash_OpTable::lookup (const char *str, unsigned int len)
{
  enum
    {
      TOTAL_KEYWORDS = 15,
      MIN_WORD_LENGTH = 5,
      MAX_WORD_LENGTH = 23,
      MIN_HASH_VALUE = 5,
      MAX_HASH_VALUE = 33,
      HASH_VALUE_RANGE = 29,
      DUPLICATES = 0,
      WORDLIST_SIZE = 20
    };

  static const TAO_operation_db_entry wordlist[] =
    {
      {"",0,0},{"",0,0},{"",0,0},{"",0,0},{"",0,0},
      {"clean", std::addressof(POA_DATABASE_MODULE::DataBase::clean_skel), nullptr},
      {"",0,0},{"",0,0},{"",0,0},{"",0,0},
      {"storeImage", std::addressof(POA_DATABASE_MODULE::DataBase::storeImage_skel), nullptr},
      {"",0,0},{"",0,0},
      {"storeProposal", std::addressof(POA_DATABASE_MODULE::DataBase::storeProposal_skel), nullptr},
      {"_get_name", std::addressof(POA_ACS::ACSComponent::_get_name_skel), 0},
      {"_interface", std::addressof(TAO_ServantBase::_interface_skel), nullptr},
      {"",0,0},
      {"setProposalStatus", std::addressof(POA_DATABASE_MODULE::DataBase::setProposalStatus_skel), nullptr},
      {"",0,0},
      {"_repository_id", std::addressof(TAO_ServantBase::_repository_id_thru_poa_skel), nullptr},
      {"_component", std::addressof(TAO_ServantBase::_component_thru_poa_skel), nullptr},
      {"",0,0},
      {"getProposals", std::addressof(POA_DATABASE_MODULE::DataBase::getProposals_skel), nullptr},
      {"_non_existent", std::addressof(TAO_ServantBase::_non_existent_thru_poa_skel), nullptr},
      {"_get_componentState", std::addressof(POA_ACS::ACSComponent::_get_componentState_skel), 0},
      {"_is_a", std::addressof(TAO_ServantBase::_is_a_thru_poa_skel), nullptr},
      {"",0,0},
      {"getProposalStatus", std::addressof(POA_DATABASE_MODULE::DataBase::getProposalStatus_skel), nullptr},
      {"",0,0},
      {"removeProposal", std::addressof(POA_DATABASE_MODULE::DataBase::removeProposal_skel), nullptr},
      {"",0,0},{"",0,0},{"",0,0},
      {"getProposalObservations", std::addressof(POA_DATABASE_MODULE::DataBase::getProposalObservations_skel), nullptr},
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      unsigned int const key = hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= MIN_HASH_VALUE)
        {
          const char *s = wordlist[key].opname;

          if (*str == *s && !ACE_OS::strncmp (str + 1, s + 1, len - 1))
            return &wordlist[key];
        }
    }
  return 0;
}

static TAO_DATABASE_MODULE_DataBase_Perfect_Hash_OpTable tao_DATABASE_MODULE_DataBase_optable;


// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/interface_ss.cpp:89



POA_DATABASE_MODULE::DataBase::DataBase ()
  : TAO_ServantBase ()
{
  this->optable_ = std::addressof(tao_DATABASE_MODULE_DataBase_optable);
}

POA_DATABASE_MODULE::DataBase::DataBase (const DataBase& rhs)
  : TAO_Abstract_ServantBase (rhs),
    TAO_ServantBase (rhs),
    POA_ACS::ACSComponent (rhs)
{
}


namespace POA_DATABASE_MODULE
{
  
  // TAO_IDL - Generated from
  // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/upcall_command_ss.cpp:79

  class storeProposal_DataBase
    : public TAO::Upcall_Command
  {
  public:
    inline storeProposal_DataBase (
      POA_DATABASE_MODULE::DataBase * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }

    void execute () override
    {
      TAO::SArg_Traits< ::CORBA::Long>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< ::CORBA::Long> (
          this->operation_details_,
          this->args_);
      
      TAO::SArg_Traits< ::TYPES::TargetList>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< ::TYPES::TargetList> (
          this->operation_details_,
          this->args_,
          1);
        
      retval =
        this->servant_->storeProposal (
          arg_1);
    }
  
  private:
    POA_DATABASE_MODULE::DataBase * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/operation_ss.cpp:167

void POA_DATABASE_MODULE::DataBase::storeProposal_skel (
  TAO_ServerRequest & server_request,
  TAO::Portable_Server::Servant_Upcall *TAO_INTERCEPTOR (servant_upcall),
  TAO_ServantBase *servant)
{TAO::SArg_Traits< ::CORBA::Long>::ret_val retval;
  TAO::SArg_Traits< ::TYPES::TargetList>::in_arg_val _tao_targets;

  TAO::Argument * const args[] =
    {
      std::addressof(retval),
      std::addressof(_tao_targets)
    };
  
  POA_DATABASE_MODULE::DataBase * const impl =
    dynamic_cast<POA_DATABASE_MODULE::DataBase *> (servant);

  if (!impl)
    {
      throw ::CORBA::INTERNAL ();
    }

  storeProposal_DataBase command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , 2
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , nullptr
                         , 0
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}


namespace POA_DATABASE_MODULE
{
  
  // TAO_IDL - Generated from
  // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/upcall_command_ss.cpp:79

  class getProposalStatus_DataBase
    : public TAO::Upcall_Command
  {
  public:
    inline getProposalStatus_DataBase (
      POA_DATABASE_MODULE::DataBase * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }

    void execute () override
    {
      TAO::SArg_Traits< ::CORBA::Long>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< ::CORBA::Long> (
          this->operation_details_,
          this->args_);
      
      TAO::SArg_Traits< ::CORBA::Long>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< ::CORBA::Long> (
          this->operation_details_,
          this->args_,
          1);
        
      retval =
        this->servant_->getProposalStatus (
          arg_1);
    }
  
  private:
    POA_DATABASE_MODULE::DataBase * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/operation_ss.cpp:167

void POA_DATABASE_MODULE::DataBase::getProposalStatus_skel (
  TAO_ServerRequest & server_request,
  TAO::Portable_Server::Servant_Upcall *TAO_INTERCEPTOR (servant_upcall),
  TAO_ServantBase *servant)
{TAO::SArg_Traits< ::CORBA::Long>::ret_val retval;
  TAO::SArg_Traits< ::CORBA::Long>::in_arg_val _tao_pid;

  TAO::Argument * const args[] =
    {
      std::addressof(retval),
      std::addressof(_tao_pid)
    };
  
  POA_DATABASE_MODULE::DataBase * const impl =
    dynamic_cast<POA_DATABASE_MODULE::DataBase *> (servant);

  if (!impl)
    {
      throw ::CORBA::INTERNAL ();
    }

  getProposalStatus_DataBase command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , 2
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , nullptr
                         , 0
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}


namespace POA_DATABASE_MODULE
{
  
  // TAO_IDL - Generated from
  // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/upcall_command_ss.cpp:79

  class removeProposal_DataBase
    : public TAO::Upcall_Command
  {
  public:
    inline removeProposal_DataBase (
      POA_DATABASE_MODULE::DataBase * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }

    void execute () override
    {
      TAO::SArg_Traits< ::CORBA::Long>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< ::CORBA::Long> (
          this->operation_details_,
          this->args_,
          1);
        
      this->servant_->removeProposal (
        arg_1);
    }
  
  private:
    POA_DATABASE_MODULE::DataBase * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/operation_ss.cpp:167

void POA_DATABASE_MODULE::DataBase::removeProposal_skel (
  TAO_ServerRequest & server_request,
  TAO::Portable_Server::Servant_Upcall *TAO_INTERCEPTOR (servant_upcall),
  TAO_ServantBase *servant)
{TAO::SArg_Traits< void>::ret_val retval;
  TAO::SArg_Traits< ::CORBA::Long>::in_arg_val _tao_pid;

  TAO::Argument * const args[] =
    {
      std::addressof(retval),
      std::addressof(_tao_pid)
    };
  
  POA_DATABASE_MODULE::DataBase * const impl =
    dynamic_cast<POA_DATABASE_MODULE::DataBase *> (servant);

  if (!impl)
    {
      throw ::CORBA::INTERNAL ();
    }

  removeProposal_DataBase command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , 2
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , nullptr
                         , 0
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}


namespace POA_DATABASE_MODULE
{
  
  // TAO_IDL - Generated from
  // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/upcall_command_ss.cpp:79

  class getProposalObservations_DataBase
    : public TAO::Upcall_Command
  {
  public:
    inline getProposalObservations_DataBase (
      POA_DATABASE_MODULE::DataBase * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }

    void execute () override
    {
      TAO::SArg_Traits< ::TYPES::ImageList>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< ::TYPES::ImageList> (
          this->operation_details_,
          this->args_);
      
      TAO::SArg_Traits< ::CORBA::Long>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< ::CORBA::Long> (
          this->operation_details_,
          this->args_,
          1);
        
      retval =
        this->servant_->getProposalObservations (
          arg_1);
    }
  
  private:
    POA_DATABASE_MODULE::DataBase * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/operation_ss.cpp:167

void POA_DATABASE_MODULE::DataBase::getProposalObservations_skel (
  TAO_ServerRequest & server_request,
  TAO::Portable_Server::Servant_Upcall *TAO_INTERCEPTOR (servant_upcall),
  TAO_ServantBase *servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const exceptions[] = 
    {
      SYSTEMErr::_tc_ProposalNotYetReadyEx
    };
  
#endif /* TAO_HAS_INTERCEPTORS */

  TAO::SArg_Traits< ::TYPES::ImageList>::ret_val retval;
  TAO::SArg_Traits< ::CORBA::Long>::in_arg_val _tao_pid;

  TAO::Argument * const args[] =
    {
      std::addressof(retval),
      std::addressof(_tao_pid)
    };
  
  POA_DATABASE_MODULE::DataBase * const impl =
    dynamic_cast<POA_DATABASE_MODULE::DataBase *> (servant);

  if (!impl)
    {
      throw ::CORBA::INTERNAL ();
    }

  getProposalObservations_DataBase command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , 2
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , 1
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}


namespace POA_DATABASE_MODULE
{
  
  // TAO_IDL - Generated from
  // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/upcall_command_ss.cpp:79

  class getProposals_DataBase
    : public TAO::Upcall_Command
  {
  public:
    inline getProposals_DataBase (
      POA_DATABASE_MODULE::DataBase * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }

    void execute () override
    {
      TAO::SArg_Traits< ::TYPES::ProposalList>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< ::TYPES::ProposalList> (
          this->operation_details_,
          this->args_);
      
      retval =
        this->servant_->getProposals ();
    }
  
  private:
    POA_DATABASE_MODULE::DataBase * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/operation_ss.cpp:167

void POA_DATABASE_MODULE::DataBase::getProposals_skel (
  TAO_ServerRequest & server_request,
  TAO::Portable_Server::Servant_Upcall *TAO_INTERCEPTOR (servant_upcall),
  TAO_ServantBase *servant)
{TAO::SArg_Traits< ::TYPES::ProposalList>::ret_val retval;

  TAO::Argument * const args[] =
    {
      std::addressof(retval)
    };
  
  POA_DATABASE_MODULE::DataBase * const impl =
    dynamic_cast<POA_DATABASE_MODULE::DataBase *> (servant);

  if (!impl)
    {
      throw ::CORBA::INTERNAL ();
    }

  getProposals_DataBase command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , 1
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , nullptr
                         , 0
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}


namespace POA_DATABASE_MODULE
{
  
  // TAO_IDL - Generated from
  // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/upcall_command_ss.cpp:79

  class setProposalStatus_DataBase
    : public TAO::Upcall_Command
  {
  public:
    inline setProposalStatus_DataBase (
      POA_DATABASE_MODULE::DataBase * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }

    void execute () override
    {
      TAO::SArg_Traits< ::CORBA::Long>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< ::CORBA::Long> (
          this->operation_details_,
          this->args_,
          1);
        
      TAO::SArg_Traits< ::CORBA::Long>::in_arg_type arg_2 =
        TAO::Portable_Server::get_in_arg< ::CORBA::Long> (
          this->operation_details_,
          this->args_,
          2);
        
      this->servant_->setProposalStatus (
        arg_1
        , arg_2);
    }
  
  private:
    POA_DATABASE_MODULE::DataBase * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/operation_ss.cpp:167

void POA_DATABASE_MODULE::DataBase::setProposalStatus_skel (
  TAO_ServerRequest & server_request,
  TAO::Portable_Server::Servant_Upcall *TAO_INTERCEPTOR (servant_upcall),
  TAO_ServantBase *servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const exceptions[] = 
    {
      SYSTEMErr::_tc_InvalidProposalStatusTransitionEx
    };
  
#endif /* TAO_HAS_INTERCEPTORS */

  TAO::SArg_Traits< void>::ret_val retval;
  TAO::SArg_Traits< ::CORBA::Long>::in_arg_val _tao_pid;
  TAO::SArg_Traits< ::CORBA::Long>::in_arg_val _tao_status;

  TAO::Argument * const args[] =
    {
      std::addressof(retval),
      std::addressof(_tao_pid),
      std::addressof(_tao_status)
    };
  
  POA_DATABASE_MODULE::DataBase * const impl =
    dynamic_cast<POA_DATABASE_MODULE::DataBase *> (servant);

  if (!impl)
    {
      throw ::CORBA::INTERNAL ();
    }

  setProposalStatus_DataBase command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , 3
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , 1
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}


namespace POA_DATABASE_MODULE
{
  
  // TAO_IDL - Generated from
  // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/upcall_command_ss.cpp:79

  class storeImage_DataBase
    : public TAO::Upcall_Command
  {
  public:
    inline storeImage_DataBase (
      POA_DATABASE_MODULE::DataBase * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }

    void execute () override
    {
      TAO::SArg_Traits< ::CORBA::Long>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< ::CORBA::Long> (
          this->operation_details_,
          this->args_,
          1);
        
      TAO::SArg_Traits< ::CORBA::Long>::in_arg_type arg_2 =
        TAO::Portable_Server::get_in_arg< ::CORBA::Long> (
          this->operation_details_,
          this->args_,
          2);
        
      TAO::SArg_Traits< ::TYPES::ImageType>::in_arg_type arg_3 =
        TAO::Portable_Server::get_in_arg< ::TYPES::ImageType> (
          this->operation_details_,
          this->args_,
          3);
        
      this->servant_->storeImage (
        arg_1
        , arg_2
        , arg_3);
    }
  
  private:
    POA_DATABASE_MODULE::DataBase * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/operation_ss.cpp:167

void POA_DATABASE_MODULE::DataBase::storeImage_skel (
  TAO_ServerRequest & server_request,
  TAO::Portable_Server::Servant_Upcall *TAO_INTERCEPTOR (servant_upcall),
  TAO_ServantBase *servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const exceptions[] = 
    {
      SYSTEMErr::_tc_ImageAlreadyStoredEx,
      SYSTEMErr::_tc_ProposalDoesNotExistEx,
      SYSTEMErr::_tc_TargetDoesNotExistEx
    };
  
#endif /* TAO_HAS_INTERCEPTORS */

  TAO::SArg_Traits< void>::ret_val retval;
  TAO::SArg_Traits< ::CORBA::Long>::in_arg_val _tao_pid;
  TAO::SArg_Traits< ::CORBA::Long>::in_arg_val _tao_tid;
  TAO::SArg_Traits< ::TYPES::ImageType>::in_arg_val _tao_image;

  TAO::Argument * const args[] =
    {
      std::addressof(retval),
      std::addressof(_tao_pid),
      std::addressof(_tao_tid),
      std::addressof(_tao_image)
    };
  
  POA_DATABASE_MODULE::DataBase * const impl =
    dynamic_cast<POA_DATABASE_MODULE::DataBase *> (servant);

  if (!impl)
    {
      throw ::CORBA::INTERNAL ();
    }

  storeImage_DataBase command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , 4
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , 3
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}


namespace POA_DATABASE_MODULE
{
  
  // TAO_IDL - Generated from
  // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/upcall_command_ss.cpp:79

  class clean_DataBase
    : public TAO::Upcall_Command
  {
  public:
    inline clean_DataBase (
      POA_DATABASE_MODULE::DataBase * servant)
      : servant_ (servant)
    {
    }

    void execute () override
    {
      this->servant_->clean ();
    }
  
  private:
    POA_DATABASE_MODULE::DataBase * const servant_;
  };
}
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/operation_ss.cpp:167

void POA_DATABASE_MODULE::DataBase::clean_skel (
  TAO_ServerRequest & server_request,
  TAO::Portable_Server::Servant_Upcall *TAO_INTERCEPTOR (servant_upcall),
  TAO_ServantBase *servant)
{TAO::SArg_Traits< void>::ret_val retval;

  TAO::Argument * const args[] =
    {
      std::addressof(retval)
    };
  
  POA_DATABASE_MODULE::DataBase * const impl =
    dynamic_cast<POA_DATABASE_MODULE::DataBase *> (servant);

  if (!impl)
    {
      throw ::CORBA::INTERNAL ();
    }

  clean_DataBase command (
    impl);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , 1
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , nullptr
                         , 0
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}




// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/interface_ss.cpp:155





::CORBA::Boolean POA_DATABASE_MODULE::DataBase::_is_a (const char* value)
{
  return
    (
      std::strcmp (value, "IDL:alma/ACS/ACSComponent:1.0") == 0 ||
      std::strcmp (value, "IDL:acsws/DATABASE_MODULE/DataBase:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
    );
}

const char* POA_DATABASE_MODULE::DataBase::_interface_repository_id () const
{
  return "IDL:acsws/DATABASE_MODULE/DataBase:1.0";
}


// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/interface_ss.cpp:394



void POA_DATABASE_MODULE::DataBase::_dispatch (
  TAO_ServerRequest & req,
  TAO::Portable_Server::Servant_Upcall* servant_upcall)
{
  this->synchronous_upcall_dispatch (req, servant_upcall, this);
}


// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/interface_ss.cpp:354



DATABASE_MODULE::DataBase *
POA_DATABASE_MODULE::DataBase::_this ()
{
  TAO_Stub_Auto_Ptr stub (this->_create_stub ());
  ::CORBA::Boolean const _tao_opt_colloc = stub->servant_orb_var ()->orb_core ()->optimize_collocation_objects ();
  ::CORBA::Object_var obj = new (std::nothrow) ::CORBA::Object (stub.get (), _tao_opt_colloc, this);
  if (obj.ptr ())
    {
      (void) stub.release ();
      return TAO::Narrow_Utils<::DATABASE_MODULE::DataBase>::unchecked_narrow (obj.in ());
    }
  return {};
}

#endif /* ifndef */

