// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v3.1.3
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_codegen.cpp:372


#include "InstrumentC.h"
#include "tao/AnyTypeCode/Null_RefCount_Policy.h"
#include "tao/AnyTypeCode/TypeCode_Constants.h"
#include "tao/AnyTypeCode/Alias_TypeCode_Static.h"
#include "tao/AnyTypeCode/Objref_TypeCode_Static.h"
#include "tao/CDR.h"
#include "tao/Exception_Data.h"
#include "tao/Invocation_Adapter.h"
#include "tao/Object_T.h"
#include "tao/CDR.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/AnyTypeCode/Any_Impl_T.h"
#include "cstring"

#if !defined (__ACE_INLINE__)
#include "InstrumentC.inl"
#endif /* !defined INLINE */
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for INSTRUMENT_MODULE::Instrument.

INSTRUMENT_MODULE::Instrument_ptr
TAO::Objref_Traits<INSTRUMENT_MODULE::Instrument>::duplicate (INSTRUMENT_MODULE::Instrument_ptr p)
{
  return INSTRUMENT_MODULE::Instrument::_duplicate (p);
}

void
TAO::Objref_Traits<INSTRUMENT_MODULE::Instrument>::release (INSTRUMENT_MODULE::Instrument_ptr p)
{
  ::CORBA::release (p);
}

INSTRUMENT_MODULE::Instrument_ptr
TAO::Objref_Traits<INSTRUMENT_MODULE::Instrument>::nil ()
{
  return INSTRUMENT_MODULE::Instrument::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<INSTRUMENT_MODULE::Instrument>::marshal (const INSTRUMENT_MODULE::Instrument_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/operation_cs.cpp:87

void
INSTRUMENT_MODULE::Instrument::cameraOn ()
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;

  TAO::Argument *_the_tao_operation_signature [] =
    {
      std::addressof(_tao_retval)
    };

  TAO::Invocation_Adapter _invocation_call (
      this,
      _the_tao_operation_signature,
      1,
      "cameraOn",
      8,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY,
      TAO::TAO_TWOWAY_INVOCATION
      ,
      TAO::TAO_SYNCHRONOUS_INVOCATION,
      false
    );

  _invocation_call.invoke (nullptr, 0);
}
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/operation_cs.cpp:87

void
INSTRUMENT_MODULE::Instrument::cameraOff ()
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;

  TAO::Argument *_the_tao_operation_signature [] =
    {
      std::addressof(_tao_retval)
    };

  TAO::Invocation_Adapter _invocation_call (
      this,
      _the_tao_operation_signature,
      1,
      "cameraOff",
      9,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY,
      TAO::TAO_TWOWAY_INVOCATION
      ,
      TAO::TAO_SYNCHRONOUS_INVOCATION,
      false
    );

  _invocation_call.invoke (nullptr, 0);
}
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/operation_cs.cpp:87

::TYPES::ImageType *
INSTRUMENT_MODULE::Instrument::takeImage (
  ::CORBA::Long exposureTime)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< ::TYPES::ImageType>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Long>::in_arg_val _tao_exposureTime (exposureTime);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      std::addressof(_tao_retval),
      std::addressof(_tao_exposureTime)
    };

  static TAO::Exception_Data
  _tao_INSTRUMENT_MODULE_Instrument_takeImage_exceptiondata [] = 
    {
      {
        "IDL:acsws/SYSTEMErr/CameraIsOffEx:1.0",
        SYSTEMErr::CameraIsOffEx::_alloc
#if TAO_HAS_INTERCEPTORS == 1
        , SYSTEMErr::_tc_CameraIsOffEx
#endif /* TAO_HAS_INTERCEPTORS */
      }
    };

  TAO::Invocation_Adapter _invocation_call (
      this,
      _the_tao_operation_signature,
      2,
      "takeImage",
      9,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
      
    );

  _invocation_call.invoke (
      _tao_INSTRUMENT_MODULE_Instrument_takeImage_exceptiondata,
      1
    );

  return _tao_retval.retn ();
}
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/operation_cs.cpp:87

void
INSTRUMENT_MODULE::Instrument::setRGB (
  const ::TYPES::RGB & rgbConfig)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::TYPES::RGB>::in_arg_val _tao_rgbConfig (rgbConfig);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      std::addressof(_tao_retval),
      std::addressof(_tao_rgbConfig)
    };

  static TAO::Exception_Data
  _tao_INSTRUMENT_MODULE_Instrument_setRGB_exceptiondata [] = 
    {
      {
        "IDL:acsws/SYSTEMErr/CameraIsOffEx:1.0",
        SYSTEMErr::CameraIsOffEx::_alloc
#if TAO_HAS_INTERCEPTORS == 1
        , SYSTEMErr::_tc_CameraIsOffEx
#endif /* TAO_HAS_INTERCEPTORS */
      }
    };

  TAO::Invocation_Adapter _invocation_call (
      this,
      _the_tao_operation_signature,
      2,
      "setRGB",
      6,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
      
    );

  _invocation_call.invoke (
      _tao_INSTRUMENT_MODULE_Instrument_setRGB_exceptiondata,
      1
    );
}
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/operation_cs.cpp:87

void
INSTRUMENT_MODULE::Instrument::setPixelBias (
  ::CORBA::Long bias)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Long>::in_arg_val _tao_bias (bias);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      std::addressof(_tao_retval),
      std::addressof(_tao_bias)
    };

  static TAO::Exception_Data
  _tao_INSTRUMENT_MODULE_Instrument_setPixelBias_exceptiondata [] = 
    {
      {
        "IDL:acsws/SYSTEMErr/CameraIsOffEx:1.0",
        SYSTEMErr::CameraIsOffEx::_alloc
#if TAO_HAS_INTERCEPTORS == 1
        , SYSTEMErr::_tc_CameraIsOffEx
#endif /* TAO_HAS_INTERCEPTORS */
      }
    };

  TAO::Invocation_Adapter _invocation_call (
      this,
      _the_tao_operation_signature,
      2,
      "setPixelBias",
      12,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
      
    );

  _invocation_call.invoke (
      _tao_INSTRUMENT_MODULE_Instrument_setPixelBias_exceptiondata,
      1
    );
}
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/operation_cs.cpp:87

void
INSTRUMENT_MODULE::Instrument::setResetLevel (
  ::CORBA::Long resetLevel)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Long>::in_arg_val _tao_resetLevel (resetLevel);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      std::addressof(_tao_retval),
      std::addressof(_tao_resetLevel)
    };

  static TAO::Exception_Data
  _tao_INSTRUMENT_MODULE_Instrument_setResetLevel_exceptiondata [] = 
    {
      {
        "IDL:acsws/SYSTEMErr/CameraIsOffEx:1.0",
        SYSTEMErr::CameraIsOffEx::_alloc
#if TAO_HAS_INTERCEPTORS == 1
        , SYSTEMErr::_tc_CameraIsOffEx
#endif /* TAO_HAS_INTERCEPTORS */
      }
    };

  TAO::Invocation_Adapter _invocation_call (
      this,
      _the_tao_operation_signature,
      2,
      "setResetLevel",
      13,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
      
    );

  _invocation_call.invoke (
      _tao_INSTRUMENT_MODULE_Instrument_setResetLevel_exceptiondata,
      1
    );
}

INSTRUMENT_MODULE::Instrument::Instrument ()
{
}
void
INSTRUMENT_MODULE::Instrument::_tao_any_destructor (void *_tao_void_pointer)
{
  Instrument *_tao_tmp_pointer =
    static_cast<Instrument *> (_tao_void_pointer);
  ::CORBA::release (_tao_tmp_pointer);
}

INSTRUMENT_MODULE::Instrument_ptr
INSTRUMENT_MODULE::Instrument::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TAO::Narrow_Utils<Instrument>::narrow (_tao_objref, "IDL:acsws/INSTRUMENT_MODULE/Instrument:1.0");
}

INSTRUMENT_MODULE::Instrument_ptr
INSTRUMENT_MODULE::Instrument::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return TAO::Narrow_Utils<Instrument>::unchecked_narrow (_tao_objref);
}

INSTRUMENT_MODULE::Instrument_ptr
INSTRUMENT_MODULE::Instrument::_nil ()
{
  return nullptr;
}

INSTRUMENT_MODULE::Instrument_ptr
INSTRUMENT_MODULE::Instrument::_duplicate (Instrument_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
INSTRUMENT_MODULE::Instrument::_tao_release (Instrument_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
INSTRUMENT_MODULE::Instrument::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:alma/ACS/ACSComponent:1.0") == 0 ||
      std::strcmp (value, "IDL:acsws/INSTRUMENT_MODULE/Instrument:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* INSTRUMENT_MODULE::Instrument::_interface_repository_id () const
{
  return "IDL:acsws/INSTRUMENT_MODULE/Instrument:1.0";
}

::CORBA::Boolean
INSTRUMENT_MODULE::Instrument::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_typecode/objref_typecode.cpp:68

static TAO::TypeCode::Objref<char const *,
                             TAO::Null_RefCount_Policy>
  _tao_tc_INSTRUMENT_MODULE_Instrument (
    ::CORBA::tk_objref,
    "IDL:acsws/INSTRUMENT_MODULE/Instrument:1.0",
    "Instrument");
  

namespace INSTRUMENT_MODULE
{
  ::CORBA::TypeCode_ptr const _tc_Instrument =
    &_tao_tc_INSTRUMENT_MODULE_Instrument;
}
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/any_op_cs.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<INSTRUMENT_MODULE::Instrument>::to_object (
      ::CORBA::Object_ptr &_tao_elem) const
  {
    _tao_elem = ::CORBA::Object::_duplicate (this->value_);
    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {



/// Copying insertion.
void
operator<<= (
  ::CORBA::Any &_tao_any,
  INSTRUMENT_MODULE::Instrument_ptr _tao_elem)
{
  INSTRUMENT_MODULE::Instrument_ptr _tao_objptr =
    INSTRUMENT_MODULE::Instrument::_duplicate (_tao_elem);
  _tao_any <<= std::addressof(_tao_objptr);
}

/// Non-copying insertion.
void
operator<<= (
  ::CORBA::Any &_tao_any,
  INSTRUMENT_MODULE::Instrument_ptr *_tao_elem)
{
  TAO::Any_Impl_T<INSTRUMENT_MODULE::Instrument>::insert (
    _tao_any,
    INSTRUMENT_MODULE::Instrument::_tao_any_destructor,
    INSTRUMENT_MODULE::_tc_Instrument,
    *_tao_elem);
}

::CORBA::Boolean
operator>>= (
    const ::CORBA::Any &_tao_any,
    INSTRUMENT_MODULE::Instrument_ptr &_tao_elem)
{
  return
    TAO::Any_Impl_T<INSTRUMENT_MODULE::Instrument>::extract (
        _tao_any,
        INSTRUMENT_MODULE::Instrument::_tao_any_destructor,
        INSTRUMENT_MODULE::_tc_Instrument,
        _tao_elem);
}

}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/cdr_op_cs.cpp:50


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const INSTRUMENT_MODULE::Instrument_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    INSTRUMENT_MODULE::Instrument_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;

  if (!(strm >> obj.inout ()))
    {
      return false;
    }
  
  // Narrow to the right type.
  _tao_objref = TAO::Narrow_Utils< ::INSTRUMENT_MODULE::Instrument>::unchecked_narrow (obj.in ());

  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL



