// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v3.1.3
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_codegen.cpp:631

#ifndef _TAO_IDL__TMP__INSTRUMENTS_CPP_
#define _TAO_IDL__TMP__INSTRUMENTS_CPP_


#include "InstrumentS.h"
#include "tao/PortableServer/Operation_Table_Perfect_Hash.h"
#include "tao/PortableServer/Upcall_Command.h"
#include "tao/PortableServer/Upcall_Wrapper.h"
#include "tao/TAO_Server_Request.h"
#include "tao/ORB_Core.h"
#include "tao/Profile.h"
#include "tao/Stub.h"
#include "tao/IFR_Client_Adapter.h"
#include "tao/Object_T.h"
#include "tao/AnyTypeCode/TypeCode.h"
#include "tao/AnyTypeCode/DynamicC.h"
#include "tao/CDR.h"
#include "tao/operation_details.h"
#include "tao/PortableInterceptor.h"
#include "ace/Dynamic_Service.h"
#include "ace/Malloc_Allocator.h"
#include "cstring"
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_interface.cpp:1853

class TAO_INSTRUMENT_MODULE_Instrument_Perfect_Hash_OpTable
  : public TAO_Perfect_Hash_OpTable
{
private:
  unsigned int hash (const char *str, unsigned int len) override;

public:
  const TAO_operation_db_entry * lookup (const char *str, unsigned int len) override;
};

/* C++ code produced by gperf version 2.8 (ACE version) */
/* Command-line: ace_gperf -m -M -J -c -C -D -E -T -f 0 -F 0,0 -a -o -t -p -K opname -L C++ -Z TAO_INSTRUMENT_MODULE_Instrument_Perfect_Hash_OpTable -N lookup */

unsigned int
TAO_INSTRUMENT_MODULE_Instrument_Perfect_Hash_OpTable::hash (const char *str, unsigned int len)
{
  static constexpr unsigned char asso_values[] =
    {
     25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
     25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
     25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
     25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
     25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
     25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
     25, 25, 25, 25, 25, 25,  0, 25, 25, 25,
     25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
     25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
     25, 25, 25, 25, 25,  0, 25,  0, 25,  0,
     10,  0, 14, 25, 25, 25, 25, 25,  0, 25,
      0, 25, 25, 25, 25,  0,  5, 25, 25, 25,
     25, 25, 25, 25, 25, 25, 25, 25,
    };
  return len + asso_values[static_cast<int>(str[len - 1])] + asso_values[static_cast<int>(str[0])];
}

const TAO_operation_db_entry *
TAO_INSTRUMENT_MODULE_Instrument_Perfect_Hash_OpTable::lookup (const char *str, unsigned int len)
{
  enum
    {
      TOTAL_KEYWORDS = 13,
      MIN_WORD_LENGTH = 5,
      MAX_WORD_LENGTH = 19,
      MIN_HASH_VALUE = 5,
      MAX_HASH_VALUE = 24,
      HASH_VALUE_RANGE = 20,
      DUPLICATES = 0,
      WORDLIST_SIZE = 18
    };

  static const TAO_operation_db_entry wordlist[] =
    {
      {"",0,0},{"",0,0},{"",0,0},{"",0,0},{"",0,0},
      {"_is_a", std::addressof(TAO_ServantBase::_is_a_thru_poa_skel), nullptr},
      {"setRGB", std::addressof(POA_INSTRUMENT_MODULE::Instrument::setRGB_skel), nullptr},
      {"",0,0},
      {"cameraOn", std::addressof(POA_INSTRUMENT_MODULE::Instrument::cameraOn_skel), nullptr},
      {"_get_name", std::addressof(POA_ACS::ACSComponent::_get_name_skel), 0},
      {"_interface", std::addressof(TAO_ServantBase::_interface_skel), nullptr},
      {"",0,0},
      {"setPixelBias", std::addressof(POA_INSTRUMENT_MODULE::Instrument::setPixelBias_skel), nullptr},
      {"setResetLevel", std::addressof(POA_INSTRUMENT_MODULE::Instrument::setResetLevel_skel), nullptr},
      {"takeImage", std::addressof(POA_INSTRUMENT_MODULE::Instrument::takeImage_skel), nullptr},
      {"_component", std::addressof(TAO_ServantBase::_component_thru_poa_skel), nullptr},
      {"",0,0},{"",0,0},
      {"_non_existent", std::addressof(TAO_ServantBase::_non_existent_thru_poa_skel), nullptr},
      {"_get_componentState", std::addressof(POA_ACS::ACSComponent::_get_componentState_skel), 0},
      {"",0,0},{"",0,0},{"",0,0},
      {"cameraOff", std::addressof(POA_INSTRUMENT_MODULE::Instrument::cameraOff_skel), nullptr},
      {"_repository_id", std::addressof(TAO_ServantBase::_repository_id_thru_poa_skel), nullptr},
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      unsigned int const key = hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= MIN_HASH_VALUE)
        {
          const char *s = wordlist[key].opname;

          if (*str == *s && !ACE_OS::strncmp (str + 1, s + 1, len - 1))
            return &wordlist[key];
        }
    }
  return 0;
}

static TAO_INSTRUMENT_MODULE_Instrument_Perfect_Hash_OpTable tao_INSTRUMENT_MODULE_Instrument_optable;


// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/interface_ss.cpp:89



POA_INSTRUMENT_MODULE::Instrument::Instrument ()
  : TAO_ServantBase ()
{
  this->optable_ = std::addressof(tao_INSTRUMENT_MODULE_Instrument_optable);
}

POA_INSTRUMENT_MODULE::Instrument::Instrument (const Instrument& rhs)
  : TAO_Abstract_ServantBase (rhs),
    TAO_ServantBase (rhs),
    POA_ACS::ACSComponent (rhs)
{
}


namespace POA_INSTRUMENT_MODULE
{
  
  // TAO_IDL - Generated from
  // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/upcall_command_ss.cpp:79

  class cameraOn_Instrument
    : public TAO::Upcall_Command
  {
  public:
    inline cameraOn_Instrument (
      POA_INSTRUMENT_MODULE::Instrument * servant)
      : servant_ (servant)
    {
    }

    void execute () override
    {
      this->servant_->cameraOn ();
    }
  
  private:
    POA_INSTRUMENT_MODULE::Instrument * const servant_;
  };
}
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/operation_ss.cpp:167

void POA_INSTRUMENT_MODULE::Instrument::cameraOn_skel (
  TAO_ServerRequest & server_request,
  TAO::Portable_Server::Servant_Upcall *TAO_INTERCEPTOR (servant_upcall),
  TAO_ServantBase *servant)
{TAO::SArg_Traits< void>::ret_val retval;

  TAO::Argument * const args[] =
    {
      std::addressof(retval)
    };
  
  POA_INSTRUMENT_MODULE::Instrument * const impl =
    dynamic_cast<POA_INSTRUMENT_MODULE::Instrument *> (servant);

  if (!impl)
    {
      throw ::CORBA::INTERNAL ();
    }

  cameraOn_Instrument command (
    impl);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , 1
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , nullptr
                         , 0
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}


namespace POA_INSTRUMENT_MODULE
{
  
  // TAO_IDL - Generated from
  // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/upcall_command_ss.cpp:79

  class cameraOff_Instrument
    : public TAO::Upcall_Command
  {
  public:
    inline cameraOff_Instrument (
      POA_INSTRUMENT_MODULE::Instrument * servant)
      : servant_ (servant)
    {
    }

    void execute () override
    {
      this->servant_->cameraOff ();
    }
  
  private:
    POA_INSTRUMENT_MODULE::Instrument * const servant_;
  };
}
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/operation_ss.cpp:167

void POA_INSTRUMENT_MODULE::Instrument::cameraOff_skel (
  TAO_ServerRequest & server_request,
  TAO::Portable_Server::Servant_Upcall *TAO_INTERCEPTOR (servant_upcall),
  TAO_ServantBase *servant)
{TAO::SArg_Traits< void>::ret_val retval;

  TAO::Argument * const args[] =
    {
      std::addressof(retval)
    };
  
  POA_INSTRUMENT_MODULE::Instrument * const impl =
    dynamic_cast<POA_INSTRUMENT_MODULE::Instrument *> (servant);

  if (!impl)
    {
      throw ::CORBA::INTERNAL ();
    }

  cameraOff_Instrument command (
    impl);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , 1
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , nullptr
                         , 0
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}


namespace POA_INSTRUMENT_MODULE
{
  
  // TAO_IDL - Generated from
  // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/upcall_command_ss.cpp:79

  class takeImage_Instrument
    : public TAO::Upcall_Command
  {
  public:
    inline takeImage_Instrument (
      POA_INSTRUMENT_MODULE::Instrument * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }

    void execute () override
    {
      TAO::SArg_Traits< ::TYPES::ImageType>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< ::TYPES::ImageType> (
          this->operation_details_,
          this->args_);
      
      TAO::SArg_Traits< ::CORBA::Long>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< ::CORBA::Long> (
          this->operation_details_,
          this->args_,
          1);
        
      retval =
        this->servant_->takeImage (
          arg_1);
    }
  
  private:
    POA_INSTRUMENT_MODULE::Instrument * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/operation_ss.cpp:167

void POA_INSTRUMENT_MODULE::Instrument::takeImage_skel (
  TAO_ServerRequest & server_request,
  TAO::Portable_Server::Servant_Upcall *TAO_INTERCEPTOR (servant_upcall),
  TAO_ServantBase *servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const exceptions[] = 
    {
      SYSTEMErr::_tc_CameraIsOffEx
    };
  
#endif /* TAO_HAS_INTERCEPTORS */

  TAO::SArg_Traits< ::TYPES::ImageType>::ret_val retval;
  TAO::SArg_Traits< ::CORBA::Long>::in_arg_val _tao_exposureTime;

  TAO::Argument * const args[] =
    {
      std::addressof(retval),
      std::addressof(_tao_exposureTime)
    };
  
  POA_INSTRUMENT_MODULE::Instrument * const impl =
    dynamic_cast<POA_INSTRUMENT_MODULE::Instrument *> (servant);

  if (!impl)
    {
      throw ::CORBA::INTERNAL ();
    }

  takeImage_Instrument command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , 2
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , 1
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}


namespace POA_INSTRUMENT_MODULE
{
  
  // TAO_IDL - Generated from
  // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/upcall_command_ss.cpp:79

  class setRGB_Instrument
    : public TAO::Upcall_Command
  {
  public:
    inline setRGB_Instrument (
      POA_INSTRUMENT_MODULE::Instrument * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }

    void execute () override
    {
      TAO::SArg_Traits< ::TYPES::RGB>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< ::TYPES::RGB> (
          this->operation_details_,
          this->args_,
          1);
        
      this->servant_->setRGB (
        arg_1);
    }
  
  private:
    POA_INSTRUMENT_MODULE::Instrument * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/operation_ss.cpp:167

void POA_INSTRUMENT_MODULE::Instrument::setRGB_skel (
  TAO_ServerRequest & server_request,
  TAO::Portable_Server::Servant_Upcall *TAO_INTERCEPTOR (servant_upcall),
  TAO_ServantBase *servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const exceptions[] = 
    {
      SYSTEMErr::_tc_CameraIsOffEx
    };
  
#endif /* TAO_HAS_INTERCEPTORS */

  TAO::SArg_Traits< void>::ret_val retval;
  TAO::SArg_Traits< ::TYPES::RGB>::in_arg_val _tao_rgbConfig;

  TAO::Argument * const args[] =
    {
      std::addressof(retval),
      std::addressof(_tao_rgbConfig)
    };
  
  POA_INSTRUMENT_MODULE::Instrument * const impl =
    dynamic_cast<POA_INSTRUMENT_MODULE::Instrument *> (servant);

  if (!impl)
    {
      throw ::CORBA::INTERNAL ();
    }

  setRGB_Instrument command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , 2
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , 1
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}


namespace POA_INSTRUMENT_MODULE
{
  
  // TAO_IDL - Generated from
  // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/upcall_command_ss.cpp:79

  class setPixelBias_Instrument
    : public TAO::Upcall_Command
  {
  public:
    inline setPixelBias_Instrument (
      POA_INSTRUMENT_MODULE::Instrument * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }

    void execute () override
    {
      TAO::SArg_Traits< ::CORBA::Long>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< ::CORBA::Long> (
          this->operation_details_,
          this->args_,
          1);
        
      this->servant_->setPixelBias (
        arg_1);
    }
  
  private:
    POA_INSTRUMENT_MODULE::Instrument * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/operation_ss.cpp:167

void POA_INSTRUMENT_MODULE::Instrument::setPixelBias_skel (
  TAO_ServerRequest & server_request,
  TAO::Portable_Server::Servant_Upcall *TAO_INTERCEPTOR (servant_upcall),
  TAO_ServantBase *servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const exceptions[] = 
    {
      SYSTEMErr::_tc_CameraIsOffEx
    };
  
#endif /* TAO_HAS_INTERCEPTORS */

  TAO::SArg_Traits< void>::ret_val retval;
  TAO::SArg_Traits< ::CORBA::Long>::in_arg_val _tao_bias;

  TAO::Argument * const args[] =
    {
      std::addressof(retval),
      std::addressof(_tao_bias)
    };
  
  POA_INSTRUMENT_MODULE::Instrument * const impl =
    dynamic_cast<POA_INSTRUMENT_MODULE::Instrument *> (servant);

  if (!impl)
    {
      throw ::CORBA::INTERNAL ();
    }

  setPixelBias_Instrument command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , 2
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , 1
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}


namespace POA_INSTRUMENT_MODULE
{
  
  // TAO_IDL - Generated from
  // /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/upcall_command_ss.cpp:79

  class setResetLevel_Instrument
    : public TAO::Upcall_Command
  {
  public:
    inline setResetLevel_Instrument (
      POA_INSTRUMENT_MODULE::Instrument * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }

    void execute () override
    {
      TAO::SArg_Traits< ::CORBA::Long>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< ::CORBA::Long> (
          this->operation_details_,
          this->args_,
          1);
        
      this->servant_->setResetLevel (
        arg_1);
    }
  
  private:
    POA_INSTRUMENT_MODULE::Instrument * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}
// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_operation/operation_ss.cpp:167

void POA_INSTRUMENT_MODULE::Instrument::setResetLevel_skel (
  TAO_ServerRequest & server_request,
  TAO::Portable_Server::Servant_Upcall *TAO_INTERCEPTOR (servant_upcall),
  TAO_ServantBase *servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const exceptions[] = 
    {
      SYSTEMErr::_tc_CameraIsOffEx
    };
  
#endif /* TAO_HAS_INTERCEPTORS */

  TAO::SArg_Traits< void>::ret_val retval;
  TAO::SArg_Traits< ::CORBA::Long>::in_arg_val _tao_resetLevel;

  TAO::Argument * const args[] =
    {
      std::addressof(retval),
      std::addressof(_tao_resetLevel)
    };
  
  POA_INSTRUMENT_MODULE::Instrument * const impl =
    dynamic_cast<POA_INSTRUMENT_MODULE::Instrument *> (servant);

  if (!impl)
    {
      throw ::CORBA::INTERNAL ();
    }

  setResetLevel_Instrument command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , 2
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , 1
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}




// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/interface_ss.cpp:155





::CORBA::Boolean POA_INSTRUMENT_MODULE::Instrument::_is_a (const char* value)
{
  return
    (
      std::strcmp (value, "IDL:alma/ACS/ACSComponent:1.0") == 0 ||
      std::strcmp (value, "IDL:acsws/INSTRUMENT_MODULE/Instrument:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
    );
}

const char* POA_INSTRUMENT_MODULE::Instrument::_interface_repository_id () const
{
  return "IDL:acsws/INSTRUMENT_MODULE/Instrument:1.0";
}


// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/interface_ss.cpp:394



void POA_INSTRUMENT_MODULE::Instrument::_dispatch (
  TAO_ServerRequest & req,
  TAO::Portable_Server::Servant_Upcall* servant_upcall)
{
  this->synchronous_upcall_dispatch (req, servant_upcall, this);
}


// TAO_IDL - Generated from
// /alma/ACS-2025APR/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/interface_ss.cpp:354



INSTRUMENT_MODULE::Instrument *
POA_INSTRUMENT_MODULE::Instrument::_this ()
{
  TAO_Stub_Auto_Ptr stub (this->_create_stub ());
  ::CORBA::Boolean const _tao_opt_colloc = stub->servant_orb_var ()->orb_core ()->optimize_collocation_objects ();
  ::CORBA::Object_var obj = new (std::nothrow) ::CORBA::Object (stub.get (), _tao_opt_colloc, this);
  if (obj.ptr ())
    {
      (void) stub.release ();
      return TAO::Narrow_Utils<::INSTRUMENT_MODULE::Instrument>::unchecked_narrow (obj.in ());
    }
  return {};
}

#endif /* ifndef */

